services:
  database:
    image: mariadb:${MARIADB_VERSION:-11.4}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app_test}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 5
      start_period: 60s

  php:
    build:
      context: .
      dockerfile: Dockerfile.ci
    volumes:
      - .:/var/www/html:rw
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-!ChangeMe!}@database:3306/${MYSQL_DATABASE:-app_test}?serverVersion=mariadb-${MARIADB_VERSION:-11.4.0}
      APP_ENV: test
      APP_SECRET: ${APP_SECRET:-6b3fbfd832e69ae0941775e377713791}
      PANTHER_WEB_SERVER_DIR: public
      PANTHER_APP_ENV: test
      PANTHER_NO_SANDBOX: 1
      PANTHER_CHROME_ARGUMENTS: --disable-dev-shm-usage --no-sandbox --headless --disable-gpu
    shm_size: '2gb'

  nginx:
    image: nginx:alpine
    ports:
      - "${WEB_PORT:-8000}:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
